name: Endor Labs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  scan:
    permissions:
      security-events: write   # Upload SARIF to GitHub
      contents: read           # Checkout
      actions: read            # Upload SARIF in private repos (GHAS)
      id-token: write          # Keyless auth to Endor Labs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Package
        run: npm install

      - name: Get latest endorctl version
        id: endor
        shell: bash
        run: |
          set -euo pipefail
          version=$(curl -s https://api.endorlabs.com/meta/version | jq -r .ClientVersion)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      # Pull Requests: PR mode
      - name: Endor Labs scan pull request
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@v1
        with:
          namespace: "endor-solutions-tsaekao.github"
          pr: true
          sarif_file: findings.sarif
          endorctl_version: "${{ steps.endor.outputs.version }}"

      # Push to default branch: monitor mode
      - name: Endor Labs scan monitor
        if: github.event_name == 'push'
        uses: endorlabs/github-action@v1
        with:
          namespace: "endor-solutions-tsaekao.github"
          pr: false
          sarif_file: findings.sarif
          endorctl_version: "${{ steps.endor.outputs.version }}"

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: findings.sarif
